[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]] #colorscheme
repo = 'altercation/vim-colors-solarized'


# TMUX
[[plugins]]
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'


[[plugins]] #
repo = 'scrooloose/nerdtree'

[[plugins]] 
repo = 'Shougo/unite.vim'

