[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]] #colorscheme
"repo = 'tomasr/molokai'
repo = 'altercation/solarized'

[[plugins]] #tree
repo = 'scrooloose/nerdtree'

[[plugins]] 
repo = 'Shougo/unite.vim'

[[plugins]] 
repo = 'itchyny/lightline.vim'

[[plugins]] #complete
repo = 'Shougo/neocomplete.vim'

[[plugins]] 
repo = 'Shougo/unite.vim'

